version: "3.9"

services:
  app:
    build: ./
    container_name: navidanindya-dev
    image: navidanindya:dev
    volumes:
      - .:/home/node/app
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=5001
      - VIRTUAL_HOST=navidanindya.localhost
    expose:
      - "5001"

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro