version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    container_name: navidanindya-dev
    image: navidanindya:dev
    volumes:
      - ./app:/home/node/app
      - /home/node/app/node_modules
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=5001
    ports:
      - 5000:5001
